import ComplementedSubspace.ComplexRealDPR

#print axioms ComplementedSubspace.norm_complex_sum_smul_le_of_subsum_bound
#print axioms ComplementedSubspace.summable_complex_smul_of_norm_le_one
#print axioms ComplementedSubspace.realifiedUnconditionalSchauderBasis
#print axioms ComplementedSubspace.hasRealDPR_of_complexUnconditionalSchauderBasis
#print axioms ComplementedSubspace.not_hasComplexUnconditionalSchauderBasis_of_real_equiv
#print axioms ComplementedSubspace.complexDualRealIsometry
#print axioms ComplementedSubspace.not_hasComplexUnconditionalSchauderBasis_dual_of_real_equiv
