import ComplementedSubspace.FiniteHilbertAverage
import ComplementedSubspace.ProductFrameWitness
import ComplementedSubspace.ProductFrameSignSample
import ComplementedSubspace.ProductFrameRowWitness

#print axioms ComplementedSubspace.finiteAverage_linearMap_norm_sq_eq_of_covariance
#print axioms ComplementedSubspace.frameWitness_euclidean_sq
#print axioms ComplementedSubspace.frameWitness_moment
#print axioms ComplementedSubspace.frameCoefficientWitness_norm
#print axioms ComplementedSubspace.normalizedFrameSign_covariance
#print axioms ComplementedSubspace.normalizedFrameSign_length_sq
#print axioms ComplementedSubspace.frameCoefficientSignSample_norm_moment_le
#print axioms ComplementedSubspace.frameCoefficientSignSample_norm_sq_average_le
#print axioms ComplementedSubspace.normalizedProductFrameRow_length_sq
#print axioms ComplementedSubspace.normalizedProductFrameRow_covariance
#print axioms ComplementedSubspace.normalizedProductFrameRow_moment
#print axioms ComplementedSubspace.frameCoefficientRow_norm
#print axioms ComplementedSubspace.frameCoefficientRow_pairing_le
#print axioms ComplementedSubspace.frameRowFunctional_norm_le
