import ComplementedSubspace.FiniteOverlapScale

#print axioms ComplementedSubspace.realFrameOverlapPenalty_compensation
#print axioms ComplementedSubspace.finite_overlap_scale_bound
#print axioms ComplementedSubspace.finite_overlap_separation_lt_half
#print axioms ComplementedSubspace.finite_overlap_selection_contradiction
#print axioms ComplementedSubspace.finite_overlap_weighted_separation_lt_one
#print axioms ComplementedSubspace.finite_overlap_weighted_selection_contradiction
#print axioms ComplementedSubspace.realFrameSignConstant_sq_le_four
#print axioms ComplementedSubspace.finite_overlap_trace_separation
#print axioms ComplementedSubspace.finite_selection_smallness
#print axioms ComplementedSubspace.finite_frame_selection_scalar_bounds
