import ComplementedSubspace.LocalHilbertHeadRenorm
import ComplementedSubspace.LocalHilbertRecursiveQuotient
import ComplementedSubspace.LocalHilbertRecursiveKernelDual

#print axioms ComplementedSubspace.HasHilbertNormWithin.pullback_contraction
#print axioms ComplementedSubspace.DualSubspacesLocallyHilbertWithin.pullback
#print axioms ComplementedSubspace.renorm_dual_subspace_dual_localHilbert
#print axioms ComplementedSubspace.exists_renorm_dual_subspace_dual_threshold
#print axioms ComplementedSubspace.headTailRenormLinear_bounds
#print axioms ComplementedSubspace.headTail_dual_subspace_dual_localHilbert
#print axioms ComplementedSubspace.exists_headTail_dual_subspace_dual_threshold
#print axioms ComplementedSubspace.recursive_headTail_dual_subspace_dual_localHilbert
#print axioms ComplementedSubspace.recursiveProfile_embedding_dual_subspaces
#print axioms ComplementedSubspace.recursiveProfile_kernel_dual_subspaces
#print axioms ComplementedSubspace.recursiveDiagonalRange_kernel_dual_subspaces
