import ComplementedSubspace.AmbientUniformConvex
import ComplementedSubspace.LpTwoParallelogram
import ComplementedSubspace.LpSubmodule
import ComplementedSubspace.FrameCoefficientReindexedRange
import ComplementedSubspace.LpHeadTail
import ComplementedSubspace.DiagonalFrameSummand

#print axioms ComplementedSubspace.finitePiLp_uniformConvexSpace
#print axioms ComplementedSubspace.ambientUniformConvexSpace
#print axioms ComplementedSubspace.ambientTailSubmodule_approxParallelogram
#print axioms ComplementedSubspace.exists_recursive_alternatingProjection_near_one
#print axioms ComplementedSubspace.lpDiagonalRangeEquiv
#print axioms ComplementedSubspace.lpDiagonalRangeEval_single
#print axioms ComplementedSubspace.lpDiagonalRange_coordinate_norm_sq
#print axioms ComplementedSubspace.RecursiveFrameSelection.frameCoefficientEvenRangeEquiv
#print axioms ComplementedSubspace.RecursiveFrameSelection.frameCoefficientOddComplementRangeEquiv
#print axioms ComplementedSubspace.lpDiagonalRangeKernelHeadTailIsometry
#print axioms ComplementedSubspace.diagonalSummand_JS
#print axioms ComplementedSubspace.diagonalSummand_SJ
#print axioms ComplementedSubspace.diagonalSummand_RJ
#print axioms ComplementedSubspace.diagonalSummand_norm_sq
