import ComplementedSubspace.PureFrameDPR

#print axioms ComplementedSubspace.lpUniformIsometryEquiv
#print axioms ComplementedSubspace.chiDPR_eq_top_of_continuousLinearEquiv
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameProjection_idempotent
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameProjection_range_chiDPR_eq_top
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameProjection_range_dual_chiDPR_eq_top
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameCoefficientRangeEquiv
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameCoefficientProfile_chiDPR_eq_top
#print axioms ComplementedSubspace.RecursiveFrameSelection.pureFrameCoefficientProfile_dual_chiDPR_eq_top
