import ComplementedSubspace.ComplexRecursiveProjection
#print axioms ComplementedSubspace.lpDiagonalRangeEquivScalar
#print axioms ComplementedSubspace.scalarIsometricConjugateRangeEquiv
#print axioms ComplementedSubspace.complexFinTensorProjection_idempotent
#print axioms ComplementedSubspace.complexFinTensorProjection_norm_le_exp
#print axioms ComplementedSubspace.RecursiveFrameSelection.predecessorComplexBlockProjection_norm_le
#print axioms ComplementedSubspace.RecursiveFrameSelection.predecessorComplexProjection_idempotent
#print axioms ComplementedSubspace.RecursiveFrameSelection.predecessorComplexProjection_norm_le
#print axioms ComplementedSubspace.RecursiveFrameSelection.one_le_predecessorComplexProjection_norm
#print axioms ComplementedSubspace.RecursiveFrameSelection.predecessorComplexProjectionRangeEquiv
#print axioms ComplementedSubspace.exists_recursive_predecessorComplexProjection_near_one
