import ComplementedSubspace.RecursiveHeadHilbert
#print axioms ComplementedSubspace.finiteDimensional_finite_lp_two
#print axioms ComplementedSubspace.hasHilbertNormWithin_finite_lp_two
#print axioms ComplementedSubspace.finitePiLp_norm_le_euclidean
#print axioms ComplementedSubspace.euclidean_norm_le_card_scale_mul_finitePiLp
#print axioms ComplementedSubspace.finitePiLp_hasHilbertNormWithin
#print axioms ComplementedSubspace.blockProfile_finiteHead_hasHilbertNormWithin
#print axioms ComplementedSubspace.recursiveProfile_finiteHead_hasHilbertNormWithin
#print axioms ComplementedSubspace.recursiveProfile_finiteHead_dual_hasHilbertNormWithin
#print axioms ComplementedSubspace.recursiveProfile_finiteHead_hilbertModel
