import ComplementedSubspace.FiniteProductObstruction
import ComplementedSubspace.FiniteDualDPRLower
#print axioms ComplementedSubspace.finite_basis_obstruction_of_frame_product
#print axioms ComplementedSubspace.frame_product_le_chiDPR_dual
