import ComplementedSubspace.SelectedProjectionSetup
#print axioms ComplementedSubspace.selectedProduct_norm_sq
#print axioms ComplementedSubspace.selectedCoefficientHilbertEquiv_norm_le_one
#print axioms ComplementedSubspace.selectedOrthogonalLift_image_contracts
#print axioms ComplementedSubspace.selectedOrthogonalLift_snd_norm_le
#print axioms ComplementedSubspace.selectedOrthogonalCoefficientMatrix_norm_le
#print axioms ComplementedSubspace.selectedOrthogonalCoefficientMatrix_mulVec
#print axioms ComplementedSubspace.selectedCoefficient_coordinate_sq_le
#print axioms ComplementedSubspace.selectedCoefficientHilbert_first_pairing
